gems:
  - name: sequel
    version: '2.12.0'
  - name: guid
    version: '0.1.1'
  - name: rack
    version: '1.0.0'
  - name: erector
    version: '0.6.7'
  - name: json-jruby
    version: '1.1.7'
  - name: activesupport
    version: '2.3.2'
  - name: collections
    version: '0.1.4'
  - name: bcrypt-ruby
    version: '2.1.1'
  - name: sqlite3-ruby
    version: '1.2.4'
  - name: mysql
    version: '2.8.1'
  - name: thor
    version: '0.11.5'
  - name: rr
